import Head from "next/head";
import Aos from "aos";
import { useEffect } from "react";

import {SocialContainer,DivToCopy,CopyItem, BtnContact, LinkedinIcon, DivIconText, GithubIcon, EmailIcon, ItemText } from '../styles/contact.elements'
 
export default function Contact() {

   useEffect(() => {
    Aos.init({
      duration: 1000,
    });
   }, []);
  
  return (
    <>
      <Head>
        <title>Mendonça - Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

          <SocialContainer>
              
              <DivToCopy data-aos="fade-right">
                  <CopyItem>Email:</CopyItem>
                  <ItemText>contato.gustavomendonca@gmail.com</ItemText>
                  <CopyItem>Telefone:</CopyItem>
                  <ItemText>(37) 984157085</ItemText>
              </DivToCopy>
              <a href="https://www.linkedin.com/in/gustavomen/"
                  target="_blank"
                  rel="noreferrer"
              >
                <BtnContact data-aos="fade-down">
                  <DivIconText>
                      <LinkedinIcon />
                      LinkedIn
                  </DivIconText> 
                  </BtnContact>
              </a>
              <a href="https://github.com/GustavoMen"
                  target="_blank"
                  rel="noreferrer"
              >
                <BtnContact data-aos="fade-down">
                  <DivIconText>
                      <GithubIcon />
                      Github
                  </DivIconText> 
                  </BtnContact>
              </a>
              <a href="mailto:contato.gustavomendonca@gmail.com"
                  target="_blank"
                  rel="noreferrer"
              >
                <BtnContact data-aos="fade-down">
                  <DivIconText>
                      <EmailIcon />
                      E-mail
                  </DivIconText> 
                  </BtnContact>
              </a>
        </SocialContainer>
    </>
  );
}
